name: ranqi
description: 燃气水表识别应用

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 图片选择和相机
  image_picker: ^1.0.4
  
  # 本地存储
  shared_preferences: ^2.2.2
  
  # HTTP请求
  http: ^1.1.0
  
  # UUID生成
  uuid: ^4.1.0
  
  # 日期格式化
  intl: ^0.18.1
  
  # 路径处理
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # 文件分享
  share_plus: ^11.1.0
  
  # WebView
  webview_flutter: ^4.4.2
  
  # 截图和图片处理
  screenshot: ^3.0.0
  
  # 保存图片到相册
  gal: ^2.3.0
  
  # 图标
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true